### ISSUE TITLE
Cove docker container shouldn't use django development server

### ISSUE THREAD

**Issue by Bjwebb** [neontribe/AG#4]
It's not recommended for production use.

We could run with gunicorn instead. On our servers we use uwsgi, but that's probably overkill for a Docker container. I'm happy to make this change if you want.

**Comment by tobybatch** [comment]
I'm happy for you to mess with the CoVE docker set as you want.

**Comment by tobybatch** [comment]
Not running a serve rany more, we pipe data in on the stdin
